server:
  port: 8082

spring:
  application:
    name: reporte-service
  datasource:
    url: jdbc:postgresql://localhost:5433/reporte_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true