server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: reporte-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/reporte_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    open-in-view: false

app:
  api-prefix: ${API_PREFIX:/api/reportes}